Update linux.yml

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -1,67 +1,104 @@
-name: Linux
+name: Linux.
 
 on:
   push:
     tags:
       - '*'
+  workflow_dispatch:
+    paths-ignore:
+      - 'docs/**'
+      - '**.md'
+      - 'changelog.txt'
+      - 'LEGAL'
+      - 'LICENSE'
+      - '.github/**'
+      - '!.github/workflows/linux.yml'
+      - 'snap/**'
+      - 'Telegram/build/**'
+      - 'Telegram/Resources/uwp/**'
+      - 'Telegram/Resources/winrc/**'
+      - 'Telegram/SourceFiles/platform/win/**'
+      - 'Telegram/SourceFiles/platform/mac/**'
+      - 'Telegram/Telegram/**'
+      - 'Telegram/configure.bat'
+      - 'Telegram/Telegram.plist'
 
 jobs:
-  build:
+
+  linux:
+    name: Rocky Linux 8
     runs-on: ubuntu-latest
-    container:
-      image: omanshkrishn/materialgram:latest
+    
+    strategy:
+      matrix:
+        defines:
+          - ""
+
+    env:
+      UPLOAD_ARTIFACT: "true"
 
     steps:
-      - name: Update System
-        run: pacman -Syu --noconfirm
+      - name: Get repository name.
+        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
 
-      - name: Set Tag Name
-        run: echo "TAGNAME=$(echo ${{ github.ref }} | cut -d '/' -f3)" >> $GITHUB_ENV 
+      - name: Clone.
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          path: ${{ env.REPO_NAME }}
 
-      - name: Build materialgram
+      - name: First set up.
         run: |
-          [ -d "/home/builder" ] && cd /home/builder || { mkdir -p /home/builder && cd /home/builder; }
-          git clone https://github.com/kukuruzka165/materialgram --recursive -b ${{ env.TAGNAME }} && cd materialgram
-          cmake \
-           -B build \
-           -G Ninja \
-           -DCMAKE_INSTALL_PREFIX="/usr" \
-           -DCMAKE_BUILD_TYPE=Release \
-           -DTDESKTOP_API_ID=${{ secrets.API_ID }} \
-           -DTDESKTOP_API_HASH=${{ secrets.API_HASH }} \
-           -DDESKTOP_APP_DISABLE_AUTOUPDATE=True \
-           -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON 
-          ninja -C build -j$(nproc --all) 
-          mkdir fakeroot && DESTDIR=$(pwd)/fakeroot ninja -C build install && cd fakeroot 
-          tar -czvf materialgram-${{ env.TAGNAME }}.tar.gz usr  
+          echo ${{ secrets.PASS }} | docker login --username ghazzor --password-stdin
+          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env
+          docker tag ghcr.io/telegramdesktop/tdesktop/centos_env tdesktop:centos_env
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
+      - name: materialgram build.
+        run: |
+          cd $REPO_NAME
+
+          DEFINE=""
+          if [ -n "${{ matrix.defines }}" ]; then
+            DEFINE="-D ${{ matrix.defines }}=ON"
+            echo Define from matrix: $DEFINE
+            echo "ARTIFACT_NAME=materialgram_${{ matrix.defines }}" >> $GITHUB_ENV
+          else
+            echo "ARTIFACT_NAME=materialgram" >> $GITHUB_ENV
+          fi
+
+          docker run --rm \
+          -v $PWD:/usr/src/tdesktop \
+          -e DEBUG=1 \
+          tdesktop:centos_env \
+          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
+          -D CMAKE_EXE_LINKER_FLAGS="-s" \
+          -D TDESKTOP_API_ID=27089606 \
+          -D TDESKTOP_API_HASH=d14ed11b1ec58dfe89233e976834ea73 \
+          -D DESKTOP_APP_DISABLE_AUTOUPDATE=True \
+          $DEFINE
+          
+      - name: Check.
+        run: |
+          filePath="$REPO_NAME/out/Release/materialgram"
+          if test -f "$filePath"; then
+            echo "Build successfully done! :)"
+
+            size=$(stat -c %s "$filePath")
+            echo "File size of ${filePath}: ${size} Bytes."
+          else
+            echo "Build error, output file does not exist."
+            exit 1
+          fi
+
+      - name: Move artifact.
+        if: env.UPLOAD_ARTIFACT == 'true'
+        run: |
+          cd $REPO_NAME/out/Release
+          mkdir artifact
+          mv materialgram artifact/
+      - uses: actions/upload-artifact@master
+        if: env.UPLOAD_ARTIFACT == 'true'
+        name: Upload artifact.
         with:
-          name: materialgram-${{ env.TAGNAME }}
-          path: /home/builder/materialgram/fakeroot/materialgram-${{ env.TAGNAME }}.tar.gz
-
-      - name: Upload artifact to Release
-        uses: softprops/action-gh-release@v2
-        if: startsWith(github.ref, 'refs/tags/')
-        with:
-          name: ${{ env.TAGNAME }}
-          token: ${{ secrets.PAT }}
-          files: /home/builder/materialgram/fakeroot/materialgram-${{ env.TAGNAME }}.tar.gz
-
-  trigger-workflow:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      
-      - name: Set Tag Name
-        run: echo "TAGNAME=$(echo ${{ github.ref }} | cut -d '/' -f3)" >> $GITHUB_ENV 
-
-      - name: Trigger repository dispatch event
-        uses: peter-evans/repository-dispatch@v3
-        with:
-          token: ${{ secrets.OKsPAT }}
-          repository: materialgram/materialgram-bin
-          event-type: new-release
-          client-payload: '{"tagname": "${{ env.TAGNAME }}", "pkgrel": "1"}'
-
+          name: ${{ env.ARTIFACT_NAME }}
+          path: ${{ env.REPO_NAME }}/out/Release/artifact/
